### ISSUE TITLE
Date类型转换异常

### ISSUE THREAD

**Issue by simonwangtx** [StarRocks/starrocks-connector-for-apache-spark#112]
connector版本：1.1.2
spark版本：3.2.0

Spark报错日志：
`Caused by: java.lang.RuntimeException: java.sql.Date is not a valid external type for schema of date
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.StaticInvoke_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Serializer.apply(ExpressionEncoder.scala:207)`

我的sr表的一个字段是date格式，spark在读取的时候报了上述错误

**Comment by slim-hub** [comment]
我也遇到了相同的问题，请问怎么解决的
